<?php

$errormsgtranslate = array(


                    '1000' => __('CONFIG ERROR. Some fundamental error in your request','allsecureexchange'),
                    '1001' => __('CONFIG ERROR. The upstream system responded with an unknown response','allsecureexchange'),
                    '1002' => __('CONFIG ERROR. Request data are malformed or missing','allsecureexchange'),
                    '1003' => __('CONFIG ERROR. Transaction could not be processed','allsecureexchange'),
                    '1004' => __('CONFIG ERROR. The request signature you provided was wrong','allsecureexchange'),
                    '1005' => __('CONFIG ERROR. The XML you provided was malformed or invalid','allsecureexchange'),
                    '1006' => __('CONFIG ERROR. Preconditions failed, e.g. capture on a failed authorize','allsecureexchange'),
                    '1007' => __('CONFIG ERROR. Something is wrong your configuration, please contact your integration engineer','allsecureexchange'),
                    '1008' => __('CONFIG ERROR. Unexpected system error','allsecureexchange'),
                    '9999' => __('CONFIG ERROR. We received an error which is not (yet) mapped to a better error code','allsecureexchange'),
                    '2001' => __('Account closed. The customer cancelled permission for his payment instrument externally','allsecureexchange'),
                    '2002' => __('User cancelled. Transaction was cancelled by customer','allsecureexchange'),
                    '2003' => __('Transaction declined. Please try again later or change the card','allsecureexchange'),
                    '2004' => __('Quota regulation. Card limit reached','allsecureexchange'),
                    '2005' => __('Transaction expired. Customer took to long to submit his payment info','allsecureexchange'),
                    '2006' => __('Insufficient funds. Card limit reached','allsecureexchange'),
                    '2007' => __('Incorrect payment info. Double check and try again','allsecureexchange'),
                    '2008' => __('Invalid card. Try with some other card','allsecureexchange'),
                    '2009' => __('Expired card. Try with some other card','allsecureexchange'),
                    '2010' => __('Invalid card. Call your bank immediately','allsecureexchange'),
                    '2011' => __('Unsupported card. Try with some other card','allsecureexchange'),
                    '2012' => __('Transaction cancelled','allsecureexchange'),
                    '2013' => __('Transaction declined. Please try again later or call your bank','allsecureexchange'),
                    '2014' => __('Transaction declined. Please try again later or call your bank','allsecureexchange'),
                    '2015' => __('Transaction declined. Please try again later or call your bank','allsecureexchange'),
                    '2016' => __('Transaction declined. Please try again later or call your bank','allsecureexchange'),
                    '2017' => __('Invalid IBAN. Double check and try again','allsecureexchange'),
                    '2018' => __('Invalid BIC. Double check and try again','allsecureexchange'),
                    '2019' => __('Customer data invalid. Double check and try again','allsecureexchange'),
                    '2020' => __('CVV required. Double check and try again','allsecureexchange'),
                    '2021' => __('3D-Secure Verification failed. Please call your bank or try with a non 3-D Secure card','allsecureexchange'),
                    '3001' => __('COMMUNICATION PROBLEM. Timeout. Try again after a short pause','allsecureexchange'),
                    '3002' => __('COMMUNICATION PROBLEM. Transaction not allowed','allsecureexchange'),
                    '3003' => __('COMMUNICATION PROBLEM. System temporary unavailable. Try again after a short pause','allsecureexchange'),
                    '3004' => __('Duplicate transaction ID','allsecureexchange'),
                    '3005' => __('COMMUNICATION PROBLEM. Try again after a short pause','allsecureexchange'),
                    '7001' => __('Schedule request is invalid','allsecureexchange'),
                    '7002' => __('Schedule request failed','allsecureexchange'),
                    '7005' => __('Schedule action is not valid','allsecureexchange'),
                    '7010' => __('RegistrationId is required','allsecureexchange'),
                    '7020' => __('RegistrationId is not valid','allsecureexchange'),
                    '7030' => __('The registrationId must point to a "register", "debit+register" or "preuth+register"','allsecureexchange'),
                    '7035' => __('Initial transaction is not a "register", "debit+register" or "preuth+register"','allsecureexchange'),
                    '7036' => __('The period between the initial and second transaction must be greater than 24 hours','allsecureexchange'),
                    '7040' => __('The scheduleId is not valid or does not match to the connector','allsecureexchange'),
                    '7050' => __('The startDateTime is invalid or older than 24 hours','allsecureexchange'),
                    '7060' => __('The continueDateTime is invalid or older than 24 hours','allsecureexchange'),
                    '7070' => __('The status of the schedule is not valid for the requested operation','allsecureexchange')
                );
?>